version: "3.9"
services:
  web:
    build: .
    container_name: nextjs_app
    ports:
      - "127.0.0.1:4000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always
