import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import "../../../public/icons/icons.css";

import { Header } from "@/components/header/Header";
import { Providers } from "../providers";
import { Footer } from "@/components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: TLanguages }>;
}>) {
  const { lang } = await params;

  return (
    <html lang={lang} suppressHydrationWarning>
      <head>
        <meta name="apple-mobile-web-app-title" content="JP Page" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers language={lang}>
          <Header language={lang} />
          <main>
            <div className="pt-[var(--header-height-default)] lg:pt-[var(--header-height-lg)] xl:pt-[var(--header-height-xl)]">
              {children}
            </div>
          </main>
          <Footer language={lang} />
        </Providers>
      </body>
    </html>
  );
}
